import assert from 'node:assert/strict';
import { DEFAULT_STATE } from '../src/lib/constants';
import { csvCell, getReceiptHkdAmount, todayForReceipts, validateItinerary } from '../src/lib/domain';
import { normalizeItinerary } from '../src/domain/trip/normalize';
import { resolveTripContext, timezoneForDestination } from '../src/domain/trip/context';
import { coordinateNumber, countryHintFor } from '../src/lib/geo';
import { fetchWeatherReport, weatherReportKey } from '../src/lib/weather';
import { stripPortableBackupState } from '../src/lib/storage';
import { mergePulledReceipts } from '../src/lib/syncMerge';
import { coordsForDay } from '../src/lib/weather/locations';
import { parseHourlyForecast } from '../src/lib/weather/providers';
import { weatherLocalTime, weatherNumber } from '../src/lib/weather/types';
import type { AppState, Receipt } from '../src/lib/types';

assert.equal(resolveTripContext('Taipei', 'JPY').countryCode, 'TW');
assert.equal(timezoneForDestination('London'), 'Europe/London');
assert.equal(timezoneForDestination('unknown city', 'Asia/Hong_Kong'), 'Asia/Hong_Kong');
assert.equal(countryHintFor({ country: 'JP' }), 'Japan');
assert.equal(countryHintFor({ country: 'North Korea' }), 'North Korea');
for (const bad of [null, undefined, '', ' ', false, Infinity, 91]) assert.equal(coordinateNumber(bad, 90), undefined);
assert.equal(coordinateNumber(0, 90), 0);
const day = { date: '2026-10-03', day: 1, region: 'Taipei', city: 'Taipei', country: 'Taiwan', spots: [{ name: 'Unknown venue', time: '10:00', type: 'food' as const, lat: null as any, lon: null as any }] };
const normalized = normalizeItinerary([day], 'audit-trip')[0];
assert.equal(normalized.timezone, 'Asia/Taipei');
assert.equal(normalized.spots[0].lat, undefined);
const validated = validateItinerary([day]);
assert.equal(validated.ok && validated.itinerary[0].spots[0].lat, undefined);
assert.equal(coordsForDay(normalized)[0].countryCode, 'TW');

const refund = { total: -1000, currency: 'JPY', hkdAmount: -75 } as Receipt;
assert.equal(getReceiptHkdAmount(refund, DEFAULT_STATE), -75);
assert.equal(getReceiptHkdAmount({ ...refund, total: 0 }, DEFAULT_STATE), 0);
assert.equal(csvCell('=HYPERLINK("https://example.invalid")'), '"\'=HYPERLINK(""https://example.invalid"")"');
assert.equal(csvCell('-125.50'), '"-125.50"');
assert.equal(csvCell('  +SUM(1,2)'), '"\'  +SUM(1,2)"');
assert.equal(csvCell('\t@SUM(1)'), '"\'\t@SUM(1)"');

const local = { id: 'local', sourceId: 'same', tripId: 't', store: 'new edit', total: 10, updatedAt: 30 } as Receipt;
const linked = mergePulledReceipts({ ...DEFAULT_STATE, receipts: [local] }, [{ ...local, id: 'cloud', supabaseId: 'cloud', notionPageId: 'notion', store: 'old remote', updatedAt: 10 }]);
assert.equal(linked.length, 1);
assert.equal(linked[0].store, 'new edit');
assert.equal(linked[0].supabaseId, 'cloud');
assert.equal(linked[0].notionPageId, 'notion');
const portable = stripPortableBackupState({ ...DEFAULT_STATE, trips: [{ ...DEFAULT_STATE.trips[0], id: 't', supabaseId: 'cloud-trip', sharing: { role: 'owner', isShared: true } as any }], receipts: [{ ...local, ownerId: 'private-owner', supabaseId: 'cloud', notionPageId: 'notion' }], deletedTripIds: ['foreign'], receiptTombstones: { foreign: {} as any }, peopleByTripId: { t: [], foreign: [] }, shareRatiosByTripId: { t: {}, foreign: {} } });
assert.equal(portable.deletedTripIds, undefined);
assert.equal(portable.receiptTombstones, undefined);
assert.equal(portable.receipts?.[0].ownerId, undefined);
assert.equal(portable.receipts?.[0].supabaseId, undefined);
assert.equal(portable.trips?.[0].sharing, undefined);
assert.deepEqual(Object.keys(portable.peopleByTripId || {}), ['t']);
assert.deepEqual(Object.keys(portable.shareRatiosByTripId || {}), ['t']);

const realNow = Date.now;
Date.now = () => Date.parse('2026-10-02T10:00:00+08:00');
const state = { ...DEFAULT_STATE, activeTripId: 'audit', trips: [{ ...DEFAULT_STATE.trips[0], id: 'audit', startDate: '2026-10-03', endDate: '2026-10-04', timezones: ['Asia/Hong_Kong'] }] } as AppState;
assert.equal(todayForReceipts(state), '2026-10-02');
state.trips[0].startDate = '2026-09-30';
state.trips[0].endDate = '2026-10-01';
assert.equal(todayForReceipts(state), '2026-10-02');
assert.equal(weatherNumber(null), undefined);
assert.equal(weatherNumber(''), undefined);
assert.equal(weatherNumber(0), 0);
assert.equal(weatherLocalTime('2026-10-03T01:00:00Z', 'America/Vancouver'), '2026-10-02T18:00');
assert.deepEqual(parseHourlyForecast({ hourly: { time: ['2026-10-03T09:00', '2026-10-03T10:00'], temperature_2m: [null, 0], precipitation_probability: [null, 0] } }, '2026-10-03').map((hour) => [hour.time, hour.temp, hour.rain]), [['2026-10-03T10:00', 0, 0]]);

const stored = new Map<string, string>();
const originalStorage = Object.getOwnPropertyDescriptor(globalThis, 'localStorage');
Object.defineProperty(globalThis, 'localStorage', { configurable: true, value: { getItem: (key: string) => stored.get(key) ?? null, setItem: (key: string, value: string) => stored.set(key, value), removeItem: (key: string) => stored.delete(key) } });
const realFetch = globalThis.fetch;
const calls: string[] = [];
let offline = false;
globalThis.fetch = async (input) => {
  const url = String(input); calls.push(url);
  if (offline) throw new Error('offline fixture');
  if (url.includes('dataType=fnd')) return Response.json({ updateTime: '2026-10-02T09:00:00+08:00', weatherForecast: [{ forecastDate: '20261003', forecastMaxtemp: { value: 32 }, forecastMintemp: { value: 24 }, forecastWeather: '多雲，有幾陣驟雨。', ForecastIcon: 63, PSR: '中高' }] });
  if (url.includes('dataType=rhrread')) return Response.json({ updateTime: '2026-10-02T09:00:00+08:00', temperature: { data: [{ place: '香港天文台', value: 28 }] } });
  if (url.startsWith('https://api.open-meteo.com/')) return Response.json({ timezone: 'Asia/Hong_Kong', hourly: { time: ['2026-10-03T09:00', '2026-10-03T10:00'], temperature_2m: [26, 27], precipitation_probability: [22, 31] } });
  if (url.includes('api.weather.gov/points/')) return Response.json({ properties: { timeZone: 'America/New_York', forecastHourly: 'https://api.weather.gov/gridpoints/OKX/1,1/forecast/hourly' } });
  if (url.includes('api.weather.gov/gridpoints/')) return Response.json({ properties: { periods: [9, 10, 11].map((hour) => ({ startTime: `2026-10-03T${String(hour).padStart(2, '0')}:00:00-04:00`, temperature: hour + 10, temperatureUnit: 'C', windSpeed: '5 to 10 mph' })) } });
  throw new Error(`Unmocked request: ${url}`);
};
try {
  const hongkong = { label: '香港', lat: 22.302, lon: 114.1743, countryCode: 'HK', timezone: 'Asia/Hong_Kong' };
  const report = await fetchWeatherReport(hongkong, '2026-10-03');
  assert.equal(report.daily?.max, 32);
  assert.equal(report.daily?.significantRain, '中高');
  assert.equal(report.hourly[0].temp, 26, 'daily min/max must never fabricate hourly temperatures');
  assert.equal(report.hourly[0].rain, 22, 'PSR must never become an invented hourly percentage');
  assert.equal(report.observation, undefined, 'today observation cannot become tomorrow forecast');
  assert.equal(report.hourlySource?.official, false);
  const firstCalls = calls.length;
  const cached = await fetchWeatherReport(hongkong, '2026-10-03');
  assert.equal(cached.cached, true);
  assert.equal(calls.length, firstCalls);
  await fetchWeatherReport(hongkong, '2026-10-03', { force: true });
  assert.ok(calls.length > firstCalls, 'refresh bypasses both persistent cache and endpoint memo');
  assert.notEqual(weatherReportKey(hongkong, '2026-10-03'), weatherReportKey({ ...hongkong, timezone: 'UTC' }, '2026-10-03'));
  const us = await fetchWeatherReport({ label: 'New York', lat: 40.71, lon: -74, countryCode: 'US', timezone: 'America/New_York' }, '2026-10-03');
  assert.deepEqual(us.hourly.map((hour) => hour.temp), [19, 20, 21], 'NWS hours keep exact times, not nearest-slot overwrites');
  assert.ok(Math.abs(us.hourly[0].windSpeed! - 16.09344) < .0001);
  offline = true;
  const stale = await fetchWeatherReport(hongkong, '2026-10-03', { force: true });
  assert.equal(stale.stale, true);
  assert.equal(stale.fetchedAt, report.fetchedAt);
  assert.match(stale.notices.join(' '), /更新失敗/);
  await assert.rejects(fetchWeatherReport({ ...hongkong, lat: 91 }, '2026-10-03'), /有效座標/);
} finally {
  globalThis.fetch = realFetch;
  Date.now = realNow;
  if (originalStorage) Object.defineProperty(globalThis, 'localStorage', originalStorage);
  else Reflect.deleteProperty(globalThis, 'localStorage');
}
console.log('compact audit regressions passed');
