-- LIVE HOTFIX PLACEHOLDER — content intentionally empty.
-- This version exists in the live project's supabase_migrations.schema_migrations
-- as `20260824033202_harden_receipt_ownership_and_photo_storage` — the live-applied
-- twin of repo migration `20260824011000_harden_receipt_ownership_and_photo_storage.sql`
-- (same change, applied out-of-band under a new timestamp; documented in the
-- 2026-08-24 CHANGELOG entry and HANDOVER). The file exists only so local history
-- matches remote and `supabase db push` stops refusing with "Remote migration
-- versions not found in local migrations directory". It never executes: the version
-- is already recorded as applied on every environment that has it.
--
-- Reconciled 2026-09-26 on branch chore/supabase-history-reconcile.
select 1;
